### PR TITLE
Some first data files

### PR DESCRIPTION
**Pull request by hendrikebbers**
Some first data files that should be used to define the first set of data that is needed.

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@giftkugel @timo0 @madmas Pages for user, talks & books done (no layout) and correct data is defined.

**Comment by hendrikebbers** [comment]
@sclassen warum sollen alle Dateien eine leere Zeile am Schluss haben? Kannst du da einen nicht-alten-unix-menschen aufklären? :)

**Comment by timo0** [comment]
@hendrikebbers May I redirect you to the famos stackoverflow question: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by hendrikebbers** [comment]
So each yml, md, etc. should end with a newline, right?

**Comment by sclassen** [comment]
Yes.
You can configure this in intelliJ so it automagically adds the empty lines for you

**Comment by hendrikebbers** [comment]
done

**Pull request merged**
